library(tidyverse)


foros <- readxl::read_excel(here::here("data/Q3870_ForosVarasMovimentacoes.xlsx")) |> 
    janitor::clean_names()

api <- readRDS(here::here("data/api.rds"))

api <- api |> 
      dplyr::filter(classe == 'Ação Penal - Procedimento Ordinário' | classe == 'Ação Penal - Procedimento Sumário')

api <- api |> 
     dplyr::mutate(cd_foro = stringr::str_sub(processo,-4) |> as.numeric()) |> 
      dplyr::filter(lubridate::year(data_recebimento) %in% c(2018,2019, 2023, 2024))

juri <- c("Crimes contra a vida","Homicídio Simples",
          "Homicídio Qualificado",
          "Aborto provocado por terceiro",
          "Feminicídio"
          )
api <- api |> 
    dplyr::filter(!assunto %in% juri)

DBI::dbWriteTable(conn, "api_filtrada",  api, overwrite = T)

DBI::dbExecute(conn,"comment on table api_filtrada is 'Essa base é filtrada para manter somente ação penal ordinário e ordinário.
               Além disso, filtrada para somente os anos 2018, 2019, 2023, 2024. Foram também excluídos os crime da competência do juri'")

entrancias <- foros |> 
     dplyr::select(cd_foro = codigo_do_foro, descricao_do_foro, entrancia) |> 
     dplyr::filter(stringr::str_detect(entrancia,"(?i)(final|interme|inicial|especial)"))  |> 
    dplyr::mutate(cd_foro = as.numeric(cd_foro)) |> 
     dplyr::distinct()


processo_entrancia <- api |> 
             dplyr::left_join(entrancias, by = "cd_foro") |> 
     dplyr::mutate(ano_recebimento = lubridate::year(data_recebimento))

DBI::dbWriteTable(conn,"api_filtrada_com_entrancia",processo_entrancia)

DBI::dbExecute(conn,"alter table api_filtrada_com_entrancia add column id int generated by default as identity")
### Para calcular a amostra, tem de haver no mínimo 30 casos.

q <- "with cte as (
     select id,  cd_processo,ano_recebimento, foro, 
     row_number() over (partition by foro order by random())::int as n
     from api_filtrada_com_entrancia d1
     where not exists(
     select from amostra d2
     where d1.cd_processo = d2.cd_processo
     )
)
select * from cte
where n >= 30
order by random()
limit 120000"
